### ISSUE TITLE
Allow Git style version numbers in image pull policy

### ISSUE THREAD

**Issue by royalsouvenir** [Selerity/sas-analytics-pro#4]
**Is your feature request related to a problem? Please describe.**
Users may be bound by organizational policies to not install the latest version but instead `n-1` or `n-2` etc.  Our bottstrap script should accommodate this in a dynamic way without needing to constantly update configuration.

**Describe the solution you'd like**
Implement checks on the `IMAGE_VERSION` variable to accept either `latest` for the most recent available image tag or Git style version assertions such as `latest~n` where `n` is the nth most recent.  The existing behavior should also be honored that an explicit version will be used if specified.

**Describe alternatives you've considered**
Alternative is to keep the functionality as is.

**Additional context**
To obtain the latest version, `apro.settings` would have:
```
IMAGE_VERSION=latest
```
Image n-1:
```
IMAGE_VERSION=latest~1
```
Specific version:
```
IMAGE_VERSION=0.5.112-20210816.1629112810612
```
If not specified, assume `latest`

**Comment by SelerityMichael** [comment]
Moved to internal.
